### ISSUE TITLE
Disable/Override Logging

### ISSUE THREAD

**Issue by brycereitano** [khaiql/dbcleaner#10]
The output printed out by the v2 version of dbcleaner is polluting my output for tests and love a way to disable it.

Either it being a way to passing in a NoOP destination/logger, or just a switch that I can flip to disable it entirely.

Example Output:
```
[Postgres] Executing command TRUNCATE TABLE countries CASCADE
[Postgres] Executing command TRUNCATE TABLE addresses CASCADE
```

**Comment by khaiql** [comment]
Agree, will update in the new release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by khaiql** [comment]
Hi, the log has been replaced by Logger option added in the new version v2.2.0, please run to get update for this

```
go get -u gopkg.in/khaiql/dbcleaner.v2
```
