### ISSUE TITLE
undefined: sync.Map

### ISSUE THREAD

**Issue by maierru** [khaiql/dbcleaner#9]
go version issue

$ go version    
go version go1.8.1 darwin/amd64

$ go test -v
vendor/gopkg.in/khaiql/dbcleaner.v2/dbcleaner.go:44: undefined: sync.Map

**Comment by khaiql** [comment]
Yeah, right, it uses sync.Map, which only available since go 1.9. For the immediate fix you can upgrade to newer version, otherwise I'll have to work around to support older version.
